openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
  description: 製品一覧および製品詳細情報を提供するAPIエンドポイント

servers:
  - url: https://your-service-url.a.run.app
    description: Cloud Run 上の本番環境

paths:
  /api/products:
    get:
      summary: 製品一覧を取得
      tags:
        - Products
      responses:
        '200':
          description: 製品リストの取得に成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: サーバーエラー

  /api/products/{id}:
    get:
      summary: 特定の製品情報を取得
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: 製品のID
      responses:
        '200':
          description: 製品情報の取得に成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: 指定された製品が存在しない
        '500':
          description: サーバーエラー

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: "p123"
        title:
          type: string
          example: "高性能ヘッドフォン"
        description:
          type: string
          example: "ノイズキャンセリング機能付きのワイヤレスヘッドフォン。"
      required:
        - id
        - title
        - description